spring:
# MySQL    
    datasource:
        url: jdbc:mysql://localhost:3306/pcm
        username: root
        password:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect 
        hibernate:
            ddl-auto: create-drop
# SQLite
    # datasource:
    #     url: jdbc:sqlite:pcm.db
    #     driver-class-name: org.sqlite.JDBC
    # jpa:
    #     database-platform: org.hibernate.dialect.SQLiteDialect
    #     hibernate:
    #         ddl-auto: create-drop     

application:
    security:
        jwt:
            secret-key: sfLtNqJt+P8RqHkwlVxHYUITNdFAW5hjYv7oo1t/rtWn/EOW5yylxSYJ8uiIOee5
            expiration: 86400000
            refresh-token:
                expiration: 604800000